### ISSUE TITLE
rename npm package to just transducers

### ISSUE THREAD

**Issue by timoxley** [jlongster/transducers.js#13]
lest somebody takes the `transducers` name. The .js is kinda redundant in the context of web and npm. Superficial? yeah.

**Comment by jlongster** [comment]
Unfortunately gozala took over that name :p so I dunno. it is a little confusing. I guess I should have moved earlier.

**Comment by timoxley** [comment]
oh well, I guess can't be resolved. No problem, was only really a suggestion because the non-.js version was still available.
