### ISSUE TITLE
Let reducer transform arg if it's not a function

### ISSUE THREAD

**Issue by Gozala** [jlongster/transducers.js#25]
Current transducers API is good, but I think it could be made better if it was:

```js
var transform = compose(
  map(x => x * 3),
  filter(x => x % 2 === 0),
  take(2)
);

transform([1, 2, 3, 4, 5]);
```

Idea is to allow transducer transform given argument if it is not an `xform`.

**Comment by jlongster** [comment]
Gozala has started his own lib with this API, as I was unsure about it: https://github.com/Gozala/transducers
