### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by tchak** [jlongster/transducers.js#26]
Would be nice if the project was using ES6 modules and then transpiled to `cjs`, `amd` and `global`. Would you accept a PR to do so ?

**Comment by jlongster** [comment]
I don't think modules would really help here; the library is literally just one file and I want to keep it that way for now. Each piece of functionality to too small to split out and it would just make it hard to work in this case.

**Comment by jlongster** [comment]
If there's anything I can do to make it easier to *consume* this lib from other module systems, let me know.
